### ISSUE TITLE
Parametrisierte Queries

### ISSUE THREAD

**Issue by wahani** [INWT/dbtools#12]
@JonathanBob @mbadicke @romanlykhnenko Ich habe jetzt mal versucht eine Möglichkeit einzubauen Abfragen zu parametrisieren. Zur Installation:

```r
devtools::install_github("inwt/dbtools", ref = "query")
```

und was damit möglich ist:

```r
query1 <- "SELECT {{ varName }} FROM {{ tableName }} WHERE primaryKey = {{ id }};"
query2 <- "SHOW TABLES;"
    
Query(query1, varName = "someVar", tableName = "someTable", .data = list(id = 1:2))
## Query:
## SELECT someVar FROM someTable WHERE primaryKey = 1;
## 
## Query:
## SELECT someVar FROM someTable WHERE primaryKey = 2;
     
tmpFile <- tempfile()
writeLines(c(query1, query2), tmpFile)
Query(file(tmpFile))
## Query:
## SELECT {{ varName }} FROM {{ tableName }} WHERE primaryKey = {{ id }};
##
## Query:
## SHOW TABLES;
```

Inspiriert durch [Liquid](http://shopify.github.io/liquid/) kann nun innerhalb der `{{` ein Ausdruck angegeben werden, der zu einem späteren Zeitpunkt mit Werten ersetzt wird. Alles innerhalb der geschweiften Klammern ist ein R-Ausdruck, kann also mit beliebigen Funktionen kombiniert werden. Das sollte dann flexibel genug sein, um MySQL-Abfragen zu parametrisieren und Tests / Formate hinzuzufügen. Ein *Query* Objekt kann dann einfach an die `sendQuery` übergeben werden. 

Vorteile:
- Abfragen können in `.sql` Dateien abgelegt werden
- Das Text-*Pasting* (was wir derzeit verwenden) wird leichter

Was haltet ihr davon?

**Comment by JonathanBob** [comment]
👍

**Comment by mbadicke** [comment]
Das sieht sehr aufgeräumt aus. 
Würde man bei diesem Ansatz auf SQL-Funktionen (sum, date etc.) generell verzichten, oder sie ebenfalls in `varName` aufnehmen?

**Comment by wahani** [comment]
Derzeit könnte man die tatsächlich in `fieldName` aufnehmen. Allerdings wäre meine Idee dort noch Funktionen zwischen zusetzen, die überprüfen, dass es sich um gültige Bezeichner handelt. Ich würde dafür folgende Wege vorschlagen:

```r
# Option 1
query <- "SELECT SUM({{ fieldName }}) FROM someTable;"
Query(query, fieldName = "someField")
## Query:
## SELECT SUM(someField) FROM someTable;

# Option 2
SUM <- function(x) paste0("SUM(", x, ")")
query <- "SELECT {{ SUM(fieldName) }} FROM someTable;"
Query(query, fieldName = "someField")
## Query:
## SELECT SUM(someField) FROM someTable;
```

**Comment by wahani** [comment]
Nun im master
