### ISSUE TITLE
Per Default Daten in 10000er Blöcken abfragen

### ISSUE THREAD

**Issue by wahani** [INWT/dbtools#17]
Bisweilen kann es zu Problemen bei Abfragen von sehr vielen Zeilen kommen. Eine Lösung im DBI Paket besteht darin, im `fetch` Befehl nur *x* Zeilen zu laden. Eventuell kann in dbtools ein sinnvoller Default-Wert verwendet werden.

**Comment by amitghosh-inwt** [comment]
Zumindest in unserer Konfiguration gab es Probleme - zumindest bei mir - frühstens ab 1 Mio. Zeilen. Ein sinnvoller Default-Wert könnte also evtl. auch eher bei 100.000 oder mehr Zeilen liegen. Evtl. wird der Overhead sonst doch größer...

**Comment by wahani** [comment]
In meinen Anwendungen werden oft um die 10 Mio Zeilen abgefragt, ohne dass es bisher Probleme gab. Eventuell also sogar noch mehr. Ich werde bei Gelegenheit mal eine Abfrage von 100.000.000 (oder viele) Zeilen versuchen und Simulieren, was (ob) das Performance Implikationen für kleinere Abfragen mit sich bringt.

**Comment by wahani** [comment]
Ich kann keinen nennenswerten Vorteil finden.
