### ISSUE TITLE
Struktur von Output: sendQuery mit simplify = FALSE 

### ISSUE THREAD

**Issue by wahani** [INWT/dbtools#27]
Derzeit bekommen wir eine Liste mit geschachtelten Listen, sortiert nach Datenbanken. Vermutlich ist eine Sortierung nach Abfragen einfacher.

**Comment by JonathanBob** [comment]
@wahani Machst Du das? Sonst würde ich mich da jetzt dran setzen, damit ich es nächste Woche im customerRating-Projekt nutzen kann.

**Comment by wahani** [comment]
:) kannst du gerne machen.

**Comment by JonathanBob** [comment]
@wahani Könntest Du Dir das bitte einmal anschauen?

In der `sendQuery` wird nun zunächst die query aufgelöst (`queryConst(query)`). Sofern es mehrere queries sind, werden diese über einen `lapply` abgearbeitet. Die `Credentials` werden erst danach berücksichtigt. Dadurch gibt es den `lapply` auf query-Ebene nur noch für den Fall von 2 oder mehr queries. 

Für den Fall `CredentialsList, SingleQuery` bekomme ich damit das gewünschte Ergebnis. Bei den anderen Fällen ist es aber irgendwie nicht rund. Ich würde ganz gern den `simplify` für Queries entfernen und `simplify` nur in Bezug auf `CredentialsList` zulassen. Aber dann passt das Beispiel in der README 

```r
queryFun <- function(state) {
  paste0("SELECT * FROM USArrests WHERE State = '", state, "';")
}

sendQuery(cred, queryFun(dat$State))
```

nicht mehr. Die Frage ist vermutlich, was man sinnvollerweise für mehr als eine Abfrage und mehr als eine Datenbank erwarten sollte.

**Comment by JonathanBob** [comment]
Ich habe ganz übersehen, dass die Umstellung der Reihenfolge wie in https://github.com/INWT/dbtools/issues/27#issuecomment-281104267 beschrieben und in #29 umgesetzt für den Fall n Abfrage auf 1 Datenbank dazu führt, dass n Verbindungen aufgebaut werden. Das ist natürlich falsch.

**Comment by JonathanBob** [comment]
Der komplizierte Weg hat also offensichtlich nicht zum Ziel geführt. Ich habe die Änderungen daher noch einmal zurückgenommen und ordne jetzt in der ansonsten gleich gebliebenen Struktur mittels queryConst(query) bereits frühzeitig zu, ob es sich um eine oder mehrere Queries handelt, so dass für den ersten Fall der lapply über die Queries nicht länger notwendig ist.

**Comment by wahani** [comment]
@JonathanBob sind die Änderungen in dem PR #29 damit noch relevant? Macht es Sinn daran weiterzuarbeiten (also ich), oder brauchen wir einen neuen Ansatz?

**Comment by wahani** [comment]
Wenn

 ```r
cred <- Credentials(
  drv = SQLite,
  dbname = c(":memory:", ":memory:")
)

dat <- sendQuery(cred, c("SELECT 1 AS x;", "SELECT 1 AS y;"), simplify = FALSE)
```

dann liefert:

```r
do.call(mapply, c(FUN = list, dat, SIMPLIFY = FALSE, recursive = FALSE))
```

die gewünschte Struktur für den Rückgabewert. Wenn wir davon ausgehen, dass dies der neue Rückgabewert ist, dann ließe sich evtl. auch das *simplify-Feature* vereinfachen.

**Comment by wahani** [comment]
In dem PR wird über die obige Idee der Output vereinfacht. Alle anderen Änderungen sind dazu da, das *simplify-Feature* dem eigenen Namen entsprechend auch im Code zu vereinfachen.
