### ISSUE TITLE
Bug in Query aus Datei

### ISSUE THREAD

**Issue by wahani** [INWT/dbtools#28]
Wenn folgende Query aus eine Datei eingelesen wird, funktioniert die R-Ausführung nicht korrekt:

```sql
SELECT ...
    {{ if(!is.null(date)) paste0("AND `e`.`date` >= '", date, "'") else ""}};
```

Folgende Variation funktioniert:

```sql
SELECT ...
    AND `e`.`date` >= '{{ if(!is.null(date)) date else ""}}';
```

**Comment by JonathanBob** [comment]
Ich glaube, dass das Problem immer dann auftritt, wenn der Ausdruck innerhalb von {{ }} die Länge 0 hat. So funktioniert obiges Beispiel bei mir mit `else ""` durchaus, aber nicht mit `else NULL`, `else character(0)` oder ähnlichem. Auch einfachere Ausdrücke scheitern mit solchen Objekten:

```SQL
SELECT ...
WHERE
    `u`.`id` IN {{ refKey }}
```

Bei Aufruf mit `dbtools::Query(file("..."), refKey = NULL)` bleibt obiger Ausdruck ebenfalls unverändert. Hier noch ein anderer interessanter Fall:

```SQL
SELECT ...
WHERE
    `u`.`id` IN {{ refKey }}
        {{ if(!is.null(date)) paste0("AND `t`.`deliveryDate` >= '", date, "'") else "abc" }}
```
 
wird bei Aufruf mit dbtools::Query(file("..."), refKey = NULL, date = NULL)` zu

```SQL
SELECT ...
WHERE
    `u`.`id` IN 123
        {{ if(!is.null(date)) paste0("AND `t`.`deliveryDate` >= '", date, "'") else "123" }}
```

Der `else`-Part wird also völlig korrekt evaluiert, allerdings dann bereits zu früh ausgegeben.

```SQL
SELECT ...
WHERE
    `u`.`id` IN {{ refKey }}
        AND {{ text }}
        {{ if(!is.null(date)) paste0("AND `t`.`deliveryDate` >= '", date, "'") else "123" }}
```

mit `dbtools::Query(file("inst/sql/payments.sql"), refKey = NULL, text = "test", date = NULL)`

wird dann entsprechend zu 

```SQL
SELECT ...
WHERE
    `u`.`id` IN test
        AND 123
        {{ if(!is.null(date)) paste0("AND `t`.`deliveryDate` >= '", date, "'") else "123" }}
```

Vielleicht hilft das ja weiter.

**Comment by wahani** [comment]
Ja, danke, das hilft. Es sieht so aus, als ob durch die NULL Werte etwas bei der Auflösung der Ausdrücke schief läuft. Ich vermute es handelt sich um ein Problem in dem templates Paket.

**Comment by JonathanBob** [comment]
Das Problem ist damit (zumindest für mich) nicht dringend, da ich mit `else ''` arbeiten kann. Dann habe ich zwar mitunter eine leere Zeile in der Query, daran stört sich MySQL aber nicht.

**Comment by wahani** [comment]
Okay, dann erst einmal so, bis das Problem in templates behoben ist.

**Comment by wahani** [comment]
Wäre denn deine Erwartung, dass bei einem NULL Wert gar keine Zeile zu sehen ist? Oder es sich eigentlich verhält wie ein leerer String?

**Comment by JonathanBob** [comment]
Ich hatte an Ersteres gedacht, aber `paste0("a", NULL)` und `paste0("a", "")` sind ja auch identisch.

**Comment by wahani** [comment]
Ist behandelt in: https://github.com/wahani/templates/issues/1und gelöst. Bald auf CRAN.
