### ISSUE TITLE
RMariaDB

### ISSUE THREAD

**Issue by JonathanBob** [INWT/dbtools#39]
@wahani 

Aus commit [4ee512c](https://github.com/rstats-db/RMySQL/commit/4ee512c9579e2a9b58d3ef2c8c68fc744d6670bb) im RMySQL-Paket ("Update README"):

> NOTE: this package is being phased out in favor of the new [RMariaDB](https://github.com/rstats-db/RMariaDB) package.

Das Paket ist allerdings (wie auch Version 0.11 von RMySQL) noch nicht auf CRAN

**Comment by JonathanBob** [comment]
Ich baue RMariaDB parallel zu MySQL in dbtools ein. Das Ganze auf dem Branch RMariaDB.

**Comment by JonathanBob** [comment]
Ich habe zwei Änderungen vorgenommen:

1. `dbtools`: `RMariaDB::MariaDB` wird jetzt re-exportiert
2. `sports-miscs`: die Credentials können jetzt mit dem Argument `MariaDB = TRUE` aufgerufen werden, wenn der MariaDB-Treiber genutzt werden soll (Bsp. `creds$inwtTipico(MariaDB = TRUE`). Default ist FALSE, so dass der Aufruf ohne Argument weiterhin funktioniert.

Das ist zunächst noch nicht hilfreich, da es in `dbtools` für `sendQuery` und `sendData` noch keine Methoden für `MariaDBConnection` gibt (bzw. auf die `DBIConnection` zurückgegriffen werden müsste).

**Comment by JonathanBob** [comment]
Es gibt jetzt Methoden für `sendQuery` und `sendData` für `signature = MySQLConnection | MariaDBConnection`. Das funktioniert leider noch nicht, da in der derzeitigen Logik von `aoos` mittels `setClassUnion("MySQLConnectionORMariaDBConnection", c("MySQLConnection", "MariaDBConnection")` eine Subklasse erzeugt wird, die beim Dispatch keine Berücksichtigung findet, weil zu beiden Klassen die Superklasse `DBIConnection` verfügbar ist. @wahani ändert bei Gelegenheit die entsprechende Funktionalität in aoos, so dass durch die Übergabe von `MySQLConnection | MariaDBConnection` zwei Methoden definiert werden, so dass der Dispatch wieder die gewünschte Methode findet.

**Comment by wahani** [comment]
Das ist leider doch nicht so einfach wie ich es mir gewünscht hatte. Es können grundsätzlich ja mehr ClassUnions in einer Signatur auftauchen. Ich muss mir darüber nochmal Gedanken machen.
