### ISSUE TITLE
sendData 'update' mode mit insert statement

### ISSUE THREAD

**Issue by wahani** [INWT/dbtools#49]
Derzeit verwenden wir einen Hack, um ein echtes update Statement abzusetzen. @phainom hatte angemerkt, dass wir das ganze auch mit einem insert file bekommen können:

1. fwrite table
2. create temp table like...
3. Insert into temp table
4. insert into table ... on duplicate key ...

Damit könnten wir wie bei allen anderen Schreiboperationen vorgehen und zunächst eine csv mit fwrite ablegen. Aus meiner Sicht ist dabei offen, wie wir nur 2 von 3 Spalten befüllen wollen.

**Comment by jonathan-inwt** [comment]
Das funktioniert ohnehin nur, wenn die Spalten, die wir nicht übergeben, ein NULL zulassen.

**Comment by wahani** [comment]
Spalten die wir nicht übergeben werden derzeit bei ihrem aktuellen Wert belassen. Das ist aus meiner Sicht unabhängig von NULLs.

**Comment by wahani** [comment]
Das Problem kann vermutlich durch die Formulierung des On DUPLICATE KEY Statements gelöst werden. Hier setzen wir eben nur die Spalten, die notwendig sind. Es bedeutet aber, dass alle anderen Spalten einen Default Wert brauchen bzw. NULL zulassen. Ansonsten funktioniert der Schreibvorgang in die Temp-Tabelle nicht.

Evtl trotzdem noch besser als die jetzige Lösung...
