### ISSUE TITLE
Semikolon in Kommentar

### ISSUE THREAD

**Issue by aneudecker** [INWT/dbtools#50]
Momentan ist es so, dass Semikolons in Kommentaren nicht ignoriert werden. Wenn ich zum Beispiel die Datei `test.sql`habe, die so aussieht:
```sql
-- select 1;
select 2;
```

Dann erzeugt `dbtools::Query(file("test.sql"))` daraus zwei Queries:
```R
> dbtools::Query(file("test.sql"))
Query:
-- select 1;

Query:
select 2;
```

Wäre es nicht sinnvoller, wenn alles nach einem Kommentar ignoriert würde?

Außerdem führen auch Leerzeichen (oder Kommentare) nach `;` zu neuen Queries.

```sql
select 1;
-- the end
```

```R
> dbtools::Query(file("test.sql"))
Query:
select 1;

Query:
-- the end;
```

**Comment by wahani** [comment]
Ich würde vorschlagen wir löschen Kommentare beim einlesen.

**Comment by jonathan-inwt** [comment]
1. alles nach `#`
2. alles nach `-- ` (Leerzeichen nach dem zweiten `-`)
3. alles zwischen `/*` und `*/`

1. und 2. lassen sich eher einfach umsetzen, 3. könnte etwas kniffliger werden. da es über das Zeilenende hinausgeht.

**Comment by jonathan-inwt** [comment]
@aneudecker Ist implementiert. Kommentare werden jetzt aus dem Code entfernt. Verschachtelte Kommentare werden nicht berücksichtigt, sind aber auch nicht zulässig. Aus der MySQL Doku:

> Nested comments are not supported, are deprecated, and will be removed in a future MySQL release. (Under some conditions, nested comments might be permitted, but usually are not, and users should avoid them.)
