### ISSUE TITLE
dbtools-Version im Repository veraltet

### ISSUE THREAD

**Issue by marinarunge** [INWT/dbtools#65]
Im INWT Repo liegt noch 

  | dbtools_0.5.2.tar.gz | 2019-03-27 10:16 | 21K |  

Da ist was beim Update schief gegangen.

**Comment by jonathan-inwt** [comment]
Das liegt daran, dass im Jenkinsfile gar kein Deplyoment des Paketes vorgesehen ist...

**Comment by jonathan-inwt** [comment]
Ich habe mit cd92324be5a88e02ad8025234df673e954c5f5ce das Jenkinsfile aktualisiert und dann mit 1ccf940c89fc824a891dde0ebcba8ab78abd506b noch einmal gefixt. Es gibt jetzt auch ein Deployment des R Pakets.

**Comment by jonathan-inwt** [comment]
![dbtools](https://user-images.githubusercontent.com/4971443/76089098-649fbc80-5fb9-11ea-8326-cdbdda5e6437.png)

**Comment by jonathan-inwt** [comment]
@marinarunge Jetzt passt es wieder.
