### ISSUE TITLE
Neue Funktion: sendData

### ISSUE THREAD

**Issue by wahani** [INWT/dbtools#7]
Hinzufügen einer oder mehrerer Funktionen zum schreiben von Daten auf Datenbanken.
- [x] Implementierung
- [x] Testen
- [x] Dokumentation
- [ ] Readme

**Comment by wahani** [comment]
Derzeitige Idee:

- `sendData` -- sendet Daten
- `replaceData` -- löscht Daten gefolgt von sendData

**Comment by wahani** [comment]
@JonathanBob Auch auf die Gafahr hin das ganze neu aufzurollen:

Wenn ich mir überlege, wie ich das Paket nutze, dann ist die primäre Funktion `sendData`. So wie wir sie jetzt verwenden, wäre es vielleicht nicht schlecht, wenn sie auch eine neue Tabelle anlegen kann, sollte es die Tabelle noch nicht geben. Das heißt, man prüft vorab ob die Tabelle existiert und steuert darüber den `append` Parameter aus. Ich denke dabei eigentlich vermehrt an andere Datenbanken als MySQL.

Das würde dann für:

- `tableCreate` -- ...
- `tableReplace` ...
- `tableAppend` ...

sprechen. Vielleicht sollten wir dafür erst einmal die Dokumentation schreiben, um zu merken, was einfach ist zu erklären.

**Comment by wahani** [comment]
```R
sendData <- function(cred, data, name, mode = c("replace", "append", "update"), ...) x

sendData(cred, USArrests, "USArrests", mode = "append")
```

**Comment by JonathanBob** [comment]
Zumindest `MySQL` bietet die Möglichkeit, Daten sowohl mit `INSERT INTO` als auch mit `REPLACE INTO` aus einer lokalen Datei in die Datenbank zu schreiben. 

```
LOAD DATA [LOW_PRIORITY | CONCURRENT] [LOCAL] INFILE 'file_name'
    [REPLACE | IGNORE]
    INTO TABLE tbl_name
    [PARTITION (partition_name,...)]
    [CHARACTER SET charset_name]
    [{FIELDS | COLUMNS}
        [TERMINATED BY 'string']
        [[OPTIONALLY] ENCLOSED BY 'char']
        [ESCAPED BY 'char']
    ]
    [LINES
        [STARTING BY 'string']
        [TERMINATED BY 'string']
    ]
    [IGNORE number {LINES | ROWS}]
    [(col_name_or_user_var,...)]
    [SET col_name = expr,...]
```

Dann wäre der workflow: `R --> txt --> Datenbank`

**Comment by amitghosh-inwt** [comment]
*Hinweis:* Mit der Funktion `LOAD DATA` arbeiten wir bereits seit langem im CJ-Projekt zum Import der AdClear-Daten. Die Funktion ist ansich sehr schnell, wenn größere Datenmengen importiert werden müssen.

**Comment by wahani** [comment]
Das wird dann interessant, wenn data.table den fwrite zu CRAN schickt. Damit hätten wir dann eine performante Lösung um aus R heraus Tabellen an Datenbanken zu senden.

Den umgekehrten Weg könnten wir im übrigen auch gehen. Zum Beispiel mit 

```SQL
SELECT * FROM table INTO OUTFILE tmp.csv;
```

und mit `fread` zum Einlesen -- da die Verbindungen über DBI ja durchaus ab und an in die Knie gezwungen werden.

**Comment by JonathanBob** [comment]
@wahani Der umgekehrte Weg

```SQL
SELECT * FROM table INTO OUTFILE tmp.csv;
```

ist nicht ohne Weiteres möglich. Laut manual gilt

> The file is created on the server host.

Und da können wir mit der Datei nichts anfangen.

Alternativ kann `mysql -e "SELECT ..." > file_name` auf der Kommandozeile verwendet werden, aber hier dauert das Erstellen der Datei (ohne anschließendes Einlesen) schon länger als `sendQuery`.

**Comment by JonathanBob** [comment]
Der Ansatz über `LOAD DATA` funktioniert leider nur über `MySQL`. In `SQLite` muss man den Weg über `INSERT/REPLACE INTO` gehen.

**Comment by JonathanBob** [comment]
data.table 1.10.0 ist bei cran. Wir könnten also auf fwrite umsteigen.

**Comment by wahani** [comment]
nun im master
)
